trigger:
  branches:
    include:
      - app

pool:
  name: 'agent1'  # Your self-hosted agent

variables:
  imageName: 'amazoncr.azurecr.io/amazon-webapp'

steps:
- checkout: self

# Maven task skipped because WAR is prebuilt
# - task: Maven@3
#   inputs:
#     mavenPomFile: 'Amazon/pom.xml'
#     goals: 'package'
#     options: '-DskipTests'

- task: Docker@2
  inputs:
    containerRegistry: 'amazon-service-connection'  # Docker Registry service connection pointing to ACR
    repository: '$(imageName)'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    tags: |
      latest

- task: AzureWebAppContainer@1
  inputs:
    azureSubscription: 'amazon-arm-connection'  # ARM service connection
    appName: 'amazonp'
    containers: '$(imageName):latest'
