trigger:
  branches:
    include:
      - app

pool:
  name: 'agent1'  # Your self-hosted agent

variables:
  imageName: 'amazon-webapp'

steps:
- checkout: self

- task: Maven@3
  inputs:
    mavenPomFile: 'Amazon/pom.xml'
    goals: 'package'
    options: '-DskipTests'

- task: Docker@2
  inputs:
    containerRegistry: 'amazon-service-connection'  # ACR service connection
    repository: '$(imageName)'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    tags: |
      latest

- task: AzureWebAppContainer@1
  inputs:
    azureSubscription: 'amazon-service-connection'  # 🔁 updated to match your existing service connection
    appName: 'amazonp'
    containers: 'amazoncr.azurecr.io/$(imageName):latest'
