trigger:
  branches:
    include:
      - app

pool:
  name: 'agent1'  # Your self-hosted agent

variables:
  imageName: 'pavani687/amazon-webapp'

steps:
- checkout: self

# Maven build skipped (WAR prebuilt)
# - task: Maven@3
#   inputs:
#     mavenPomFile: 'Amazon/pom.xml'
#     goals: 'package'
#     options: '-DskipTests'

- task: Docker@2
  inputs:
    containerRegistry: 'docker-hub-connection'  # Docker Hub service connection
    repository: '$(imageName)'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    tags: |
      latest

- task: AzureWebAppContainer@1
  inputs:
    azureSubscription: 'amazon-arm-connection'  # Azure subscription connection
    appName: 'amazonp'
    containers: 'pavani687/amazon-webapp:latest'
