# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
name: Build and deploy WAR app to Azure Web App - amazonp1

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'microsoft'

      - name: Build entire project (multi-module)
        run: mvn clean package
        working-directory: Amazon  # Build from the parent folder

      - name: Upload WAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: war-app
          path: Amazon/Amazon-Web/target/Amazon.war  # WAR location

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Download WAR artifact
        uses: actions/download-artifact@v4
        with:
          name: war-app

      - name: Deploy WAR to Azure Web App
        run: |
          az webapp deploy --resource-group practice-p --name amazonp1 --type war --src-path Amazon.war



